// Gerado automaticamente por update-maps.js. Não edite este arquivo diretamente.
window.MINDMAPS_DATA = [
  {
    "id": "tutorial",
    "title": "🧠 MindFlow AI - Tutorial",
    "filename": "tutorial.md",
    "content": "# 🧠 MindFlow AI - Tutorial\n\n## 💡 Como Funciona\n- **Muito Leve**: Carrega instantaneamente sem travar o seu PC durante as lives/gravações.\n- **Feito em Markdown**: Cada linha e recuo criam novos nós e conexões de forma lógica.\n- **Foco em Vídeos**: Interface limpa e minimalista feita para aparecer bem no YouTube.\n\n## 🤖 Integração com IA\n- **Geração Direta**: Você me diz o tema no chat do Antigravity.\n- **Atualização Automática**: Eu crio o arquivo `.md` na pasta `maps` e atualizo o app.\n- **Sem Esforço**: Basta atualizar a página e o mapa estará pronto para o vídeo!\n\n## ⚙️ Controles\n- **Arrastar**: Clique e arraste para navegar pelo mapa.\n- **Zoom**: Use a rodinha do mouse ou os botões de controle.\n- **Expandir/Recolher**: Clique nos círculos dos nós para recolher ou expandir subitens.\n\n## ⌨️ Atalhos Rápidos\n- **P / F**: Modo Apresentação (esconde menus, foca 100% no mapa).\n- **E**: Abrir/Fechar Editor Lateral.\n- **S**: Salvar rascunho atual.\n- **0 (Zero)**: Centralizar e ajustar zoom.\n\n## 🎨 Temas para YouTube\n- **Cyberpunk Neon**: Estilo futurista escuro com cores brilhantes.\n- **YouTube Presenter**: Alto contraste e máxima legibilidade para vídeos.\n- **Nordic Forest**: Cores quentes e relaxantes.\n- **Minimal Slate**: Design limpo e moderno.\n- **Creamy Light**: Tema claro e elegante.\n"
  },
  {
    "id": "youtube-mapas-mentais",
    "title": "Vídeos do YouTube com Mapas Mentais + IA",
    "filename": "youtube-mapas-mentais.md",
    "content": "# Vídeos do YouTube com Mapas Mentais + IA\n\n## 📝 Planejamento do Vídeo\n- **Escolha do Tema**\n  - Pesquisa de Palavras-chave\n  - Análise de concorrentes no YouTube\n  - Validação da demanda do público\n- **Estruturação do Roteiro**\n  - Gancho (Primeiros 30 segundos)\n  - Conteúdo Principal (Problema + Solução)\n  - CTA (Call to Action - Se inscrever e Comentar)\n- **Criação do Mapa Mental**\n  - Enviar tema para a IA (Antigravity)\n  - Revisar nós principais\n  - Ajustar visual no MindFlow\n\n## 🎥 Produção e Gravação\n- **Configuração do Ambiente**\n  - Iluminação de 3 pontos\n  - Redução de ruído acústico\n  - Fundo limpo e organizado\n- **Configuração da Tela**\n  - Resolução 1080p ou 4K\n  - MindFlow em Modo Tela Cheia (Tecla P)\n  - Zoom ajustado para leitura fácil em celulares (Tecla 0)\n- **Performance na Câmera**\n  - Olhar diretamente para a lente\n  - Pausas estratégicas para cortes de edição\n  - Uso de gestos ao apontar para o mapa\n\n## 🛠️ MindFlow AI - Funcionalidades\n- **Alta Legibilidade**\n  - Tema YouTube Presenter (Fundo escuro, alto contraste)\n  - Fontes modernas e nítidas\n- **Interatividade ao Vivo**\n  - Esconder/revelar ramos clicando nos círculos\n  - Foco dinâmico durante a explicação\n- **Simplicidade Técnica**\n  - Sem necessidade de banco de dados\n  - Carregamento instantâneo via HTML/JS\n\n## 🚀 Pós-Produção e SEO\n- **Edição de Vídeo**\n  - Cortes de respiração e erros\n  - Inserção de Zoom dinâmico nos ramos do mapa\n  - Sound design sutil nas transições\n- **Publicação Otimizada**\n  - Títulos baseados em curiosidade + benefício\n  - Thumbnails de alto contraste (geradas por IA)\n  - Descrição com capítulos e links úteis\n"
  }
];